AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LogSubGenApp

  Sample SAM Template for LogSubGenApp

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 128
    Tags:
      Publisher: AWS
      Department: IT
      CostCenter: "12345"
      Owner: "PBKN"
      Project: "LogSubGenApp"

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.App::handleRequest
      Runtime: java8.al2
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/

  HelloWorldFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${HelloWorldFunction}"
      RetentionInDays: 7
      Tags:
        - Key: Publisher
          Value: AWS
        - Key: Department
          Value: IT
        - Key: CostCenter
          Value: "12345"
        - Key: Owner
          Value: "PBKN"
        - Key: Project
          Value: "LogSubGenApp"


  ErrorSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "ErrorNotification-SNS"
      Tags:
        - Key: Publisher
          Value: AWS
        - Key: Department
          Value: IT
        - Key: CostCenter
          Value: "12345"
        - Key: Owner
          Value: "PBKN"
        - Key: Project
          Value: "LogSubGenApp"
  ErrorSubscription1:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: ravichandran.prabhakaran@gmail.com
      Protocol: email
      TopicArn: !Ref 'ErrorSNSTopic'
  ErrorSubscription2:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: pbkn@whysurfswim.com
      Protocol: email
      TopicArn: !Ref 'ErrorSNSTopic'

  ErrorFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "ErrorFunction-Role"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"

  ErrorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ErrorFunction
      Handler: error.ErrorNotif::handleRequest
      Role:  !GetAtt ErrorFunctionRole.Arn
      Runtime: java8.al2
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
          SNS_TOPIC_ARN: !Ref ErrorSNSTopic
      Events: #LogSubscription filter will be automatically added by SAM using this event
        CWLog:
          Type: CloudWatchLogs
          Properties:
            LogGroupName:
              Ref: HelloWorldFunctionLogGroup
            FilterPattern: '?Error ?error ?Fail ?fail ?Invalid ?invalid ?Exception ?exception'

  ErrorFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ErrorFunction}"
      RetentionInDays: 7
      Tags:
        - Key: Publisher
          Value: AWS
        - Key: Department
          Value: IT
        - Key: CostCenter
          Value: "12345"
        - Key: Owner
          Value: "PBKN"
        - Key: Project
          Value: "LogSubGenApp"


Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  ErrorFunction:
    Description: "Error Lambda Function ARN"
    Value: !GetAtt ErrorFunction.Arn
  ErrorFunctionIamRole:
    Description: "Explicit IAM Role created for Error function"
    Value: !GetAtt ErrorFunctionRole.Arn
  ErrorSNSTopic:
    Description: The ARN of the created SNS topic
    Value: !Ref ErrorSNSTopic
